from typing import Any, Sequence

from pandas import DataFrame

class Schema: ...

class ChunkedArray: ...

class Table:
    @property
    def column_names(self) -> list[str]: ...
    @property
    def num_columns(self) -> int: ...
    @property
    def num_rows(self) -> int: ...
    @property
    def schema(self) -> Schema: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    def column(self, i: int | str) -> ChunkedArray: ...
    def combine_chunks(self, memory_pool: Any | None = None) -> Table: ...
    def select(self, columns: Sequence[int | str]) -> Table: ...
    def slice(self, offset: int = 0, length: int | None = None) -> Table: ...
    def to_pandas(self, **kwargs: Any) -> DataFrame: ...
