version: 2

builds:
  - id: renart
    binary: renart
    main: ./
    flags:
      - -trimpath
      - -tags=bruin_no_duckdb
    ldflags:
      - -s -w -X main.version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

  - id: renart-duckdb-linux-amd64
    binary: renart
    main: ./
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
      - -tags=no_duckdb_arrow
    ldflags:
      - -s -w -X main.version={{ .Version }}
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: renart-archives
    builds:
      - renart
      - renart-duckdb-linux-amd64
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

release:
  make_latest: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
