// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storedb

import (
	"database/sql"
)

type PipelineRun struct {
	ID          string
	PipelineID  string
	Pipeline    string
	Environment string
	Trigger     string
	Status      string
	WinStart    sql.NullString
	WinEnd      sql.NullString
	StartedAt   sql.NullString
	FinishedAt  sql.NullString
	Error       sql.NullString
	LogRef      sql.NullString
}

type PipelineRunLog struct {
	RunID string
	Seq   int64
	At    string
	Line  string
}

type PipelineRunStep struct {
	RunID      string
	Asset      string
	Status     string
	StartedAt  sql.NullString
	FinishedAt sql.NullString
	Error      sql.NullString
}

type PipelineScheduleSetting struct {
	PipelineID string
	Enabled    int64
	UpdatedAt  string
}

type ScheduleWatermark struct {
	Pipeline string
	UpTo     string
}
