// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package storedb

import (
	"context"
	"database/sql"
)

const appendRunLog = `-- name: AppendRunLog :exec
INSERT INTO pipeline_run_logs (run_id, at, line)
VALUES (?1, ?2, ?3)
`

type AppendRunLogParams struct {
	RunID string
	At    string
	Line  string
}

func (q *Queries) AppendRunLog(ctx context.Context, arg AppendRunLogParams) error {
	_, err := q.db.ExecContext(ctx, appendRunLog, arg.RunID, arg.At, arg.Line)
	return err
}

const countActiveRuns = `-- name: CountActiveRuns :one
SELECT COUNT(*)
FROM pipeline_runs
WHERE pipeline_id = ?1 AND status IN (?2, ?3)
`

type CountActiveRunsParams struct {
	PipelineID    string
	QueuedStatus  string
	RunningStatus string
}

func (q *Queries) CountActiveRuns(ctx context.Context, arg CountActiveRunsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveRuns, arg.PipelineID, arg.QueuedStatus, arg.RunningStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnvSchedules = `-- name: CountEnvSchedules :one
SELECT COUNT(*) FROM renart_schedules
`

func (q *Queries) CountEnvSchedules(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnvSchedules)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRuns = `-- name: CountRuns :one
SELECT COUNT(*)
FROM pipeline_runs
WHERE (CAST(?1 AS TEXT) = '' OR pipeline_id = CAST(?1 AS TEXT))
  AND (
    CAST(?2 AS TEXT) = ''
    OR (CAST(?2 AS TEXT) = 'default' AND (environment = CAST(?2 AS TEXT) OR environment = ''))
    OR (CAST(?2 AS TEXT) <> 'default' AND environment = CAST(?2 AS TEXT))
  )
  AND (CAST(?3 AS TEXT) = '' OR status = CAST(?3 AS TEXT))
  AND (
    CAST(?4 AS TEXT) = ''
    OR LOWER(id) LIKE CAST(?4 AS TEXT)
    OR LOWER(pipeline) LIKE CAST(?4 AS TEXT)
    OR LOWER(pipeline_id) LIKE CAST(?4 AS TEXT)
  )
`

type CountRunsParams struct {
	PipelineID  string
	Environment string
	Status      string
	QueryLike   string
}

func (q *Queries) CountRuns(ctx context.Context, arg CountRunsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRuns,
		arg.PipelineID,
		arg.Environment,
		arg.Status,
		arg.QueryLike,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRun = `-- name: CreateRun :exec
INSERT INTO pipeline_runs (id, pipeline_id, pipeline, environment, trigger, status, win_start, win_end, started_at, finished_at, error, log_ref, snapshot_version_id, river_job_id, full_refresh, backfill, sensor_mode, execution_context_resolved)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18)
`

type CreateRunParams struct {
	ID                       string
	PipelineID               string
	Pipeline                 string
	Environment              string
	Trigger                  string
	Status                   string
	WinStart                 sql.NullString
	WinEnd                   sql.NullString
	StartedAt                sql.NullString
	FinishedAt               sql.NullString
	Error                    sql.NullString
	LogRef                   sql.NullString
	SnapshotVersionID        sql.NullString
	RiverJobID               sql.NullInt64
	FullRefresh              int64
	Backfill                 int64
	SensorMode               string
	ExecutionContextResolved int64
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) error {
	_, err := q.db.ExecContext(ctx, createRun,
		arg.ID,
		arg.PipelineID,
		arg.Pipeline,
		arg.Environment,
		arg.Trigger,
		arg.Status,
		arg.WinStart,
		arg.WinEnd,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Error,
		arg.LogRef,
		arg.SnapshotVersionID,
		arg.RiverJobID,
		arg.FullRefresh,
		arg.Backfill,
		arg.SensorMode,
		arg.ExecutionContextResolved,
	)
	return err
}

const finishOpenRunSteps = `-- name: FinishOpenRunSteps :exec
UPDATE pipeline_run_steps
SET status = ?1,
    finished_at = ?2,
    error = CASE WHEN CAST(?3 AS TEXT) = '' THEN error ELSE CAST(?3 AS TEXT) END
WHERE run_id = ?4 AND finished_at IS NULL
`

type FinishOpenRunStepsParams struct {
	Status     string
	FinishedAt sql.NullString
	Error      string
	RunID      string
}

func (q *Queries) FinishOpenRunSteps(ctx context.Context, arg FinishOpenRunStepsParams) error {
	_, err := q.db.ExecContext(ctx, finishOpenRunSteps,
		arg.Status,
		arg.FinishedAt,
		arg.Error,
		arg.RunID,
	)
	return err
}

const finishRun = `-- name: FinishRun :exec
UPDATE pipeline_runs
SET status = ?1, finished_at = ?2, error = ?3
WHERE id = ?4
`

type FinishRunParams struct {
	Status     string
	FinishedAt sql.NullString
	Error      sql.NullString
	ID         string
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) error {
	_, err := q.db.ExecContext(ctx, finishRun,
		arg.Status,
		arg.FinishedAt,
		arg.Error,
		arg.ID,
	)
	return err
}

const getEnvSchedule = `-- name: GetEnvSchedule :one
SELECT pipeline_id, environment, snapshot_version_id, cron, timezone, vars, catchup_policy, status, archived_reason, next_run_at, created_at, updated_at
FROM renart_schedules
WHERE pipeline_id = ?1 AND environment = ?2
`

type GetEnvScheduleParams struct {
	PipelineID  string
	Environment string
}

func (q *Queries) GetEnvSchedule(ctx context.Context, arg GetEnvScheduleParams) (RenartSchedule, error) {
	row := q.db.QueryRowContext(ctx, getEnvSchedule, arg.PipelineID, arg.Environment)
	var i RenartSchedule
	err := row.Scan(
		&i.PipelineID,
		&i.Environment,
		&i.SnapshotVersionID,
		&i.Cron,
		&i.Timezone,
		&i.Vars,
		&i.CatchupPolicy,
		&i.Status,
		&i.ArchivedReason,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, pipeline_id, pipeline, environment, trigger, status, win_start, win_end, started_at, finished_at, error, log_ref, snapshot_version_id, recovery_pending, river_job_id, full_refresh, backfill, sensor_mode, execution_context_resolved
FROM pipeline_runs
WHERE id = ?1
`

func (q *Queries) GetRun(ctx context.Context, id string) (PipelineRun, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Pipeline,
		&i.Environment,
		&i.Trigger,
		&i.Status,
		&i.WinStart,
		&i.WinEnd,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.LogRef,
		&i.SnapshotVersionID,
		&i.RecoveryPending,
		&i.RiverJobID,
		&i.FullRefresh,
		&i.Backfill,
		&i.SensorMode,
		&i.ExecutionContextResolved,
	)
	return i, err
}

const getScheduleEnabled = `-- name: GetScheduleEnabled :one
SELECT enabled
FROM pipeline_schedule_settings
WHERE pipeline_id = ?1
`

func (q *Queries) GetScheduleEnabled(ctx context.Context, pipelineID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getScheduleEnabled, pipelineID)
	var enabled int64
	err := row.Scan(&enabled)
	return enabled, err
}

const getScheduleWatermark = `-- name: GetScheduleWatermark :one
SELECT up_to
FROM schedule_watermarks
WHERE pipeline = ?1
`

func (q *Queries) GetScheduleWatermark(ctx context.Context, pipeline string) (string, error) {
	row := q.db.QueryRowContext(ctx, getScheduleWatermark, pipeline)
	var up_to string
	err := row.Scan(&up_to)
	return up_to, err
}

const listEnvSchedules = `-- name: ListEnvSchedules :many
SELECT pipeline_id, environment, snapshot_version_id, cron, timezone, vars, catchup_policy, status, archived_reason, next_run_at, created_at, updated_at
FROM renart_schedules
ORDER BY pipeline_id, environment
`

func (q *Queries) ListEnvSchedules(ctx context.Context) ([]RenartSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listEnvSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RenartSchedule
	for rows.Next() {
		var i RenartSchedule
		if err := rows.Scan(
			&i.PipelineID,
			&i.Environment,
			&i.SnapshotVersionID,
			&i.Cron,
			&i.Timezone,
			&i.Vars,
			&i.CatchupPolicy,
			&i.Status,
			&i.ArchivedReason,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunLogs = `-- name: ListRunLogs :many
SELECT at, line
FROM pipeline_run_logs
WHERE run_id = ?1
ORDER BY seq ASC
`

type ListRunLogsRow struct {
	At   string
	Line string
}

func (q *Queries) ListRunLogs(ctx context.Context, runID string) ([]ListRunLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunLogs, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunLogsRow
	for rows.Next() {
		var i ListRunLogsRow
		if err := rows.Scan(&i.At, &i.Line); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunSteps = `-- name: ListRunSteps :many
SELECT run_id, asset, status, started_at, finished_at, error
FROM pipeline_run_steps
WHERE run_id = ?1
ORDER BY COALESCE(started_at, finished_at, '') ASC, asset ASC
`

func (q *Queries) ListRunSteps(ctx context.Context, runID string) ([]PipelineRunStep, error) {
	rows, err := q.db.QueryContext(ctx, listRunSteps, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PipelineRunStep
	for rows.Next() {
		var i PipelineRunStep
		if err := rows.Scan(
			&i.RunID,
			&i.Asset,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, pipeline_id, pipeline, environment, trigger, status, win_start, win_end, started_at, finished_at, error, log_ref, snapshot_version_id, recovery_pending, river_job_id, full_refresh, backfill, sensor_mode, execution_context_resolved
FROM pipeline_runs
WHERE (CAST(?1 AS TEXT) = '' OR pipeline_id = CAST(?1 AS TEXT))
  AND (
    CAST(?2 AS TEXT) = ''
    OR (CAST(?2 AS TEXT) = 'default' AND (environment = CAST(?2 AS TEXT) OR environment = ''))
    OR (CAST(?2 AS TEXT) <> 'default' AND environment = CAST(?2 AS TEXT))
  )
  AND (CAST(?3 AS TEXT) = '' OR status = CAST(?3 AS TEXT))
  AND (
    CAST(?4 AS TEXT) = ''
    OR LOWER(id) LIKE CAST(?4 AS TEXT)
    OR LOWER(pipeline) LIKE CAST(?4 AS TEXT)
    OR LOWER(pipeline_id) LIKE CAST(?4 AS TEXT)
  )
ORDER BY COALESCE(started_at, '') DESC, id DESC
LIMIT ?6 OFFSET ?5
`

type ListRunsParams struct {
	PipelineID  string
	Environment string
	Status      string
	QueryLike   string
	Offset      int64
	Limit       int64
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]PipelineRun, error) {
	rows, err := q.db.QueryContext(ctx, listRuns,
		arg.PipelineID,
		arg.Environment,
		arg.Status,
		arg.QueryLike,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PipelineRun
	for rows.Next() {
		var i PipelineRun
		if err := rows.Scan(
			&i.ID,
			&i.PipelineID,
			&i.Pipeline,
			&i.Environment,
			&i.Trigger,
			&i.Status,
			&i.WinStart,
			&i.WinEnd,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
			&i.LogRef,
			&i.SnapshotVersionID,
			&i.RecoveryPending,
			&i.RiverJobID,
			&i.FullRefresh,
			&i.Backfill,
			&i.SensorMode,
			&i.ExecutionContextResolved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRunRunning = `-- name: MarkRunRunning :exec
UPDATE pipeline_runs
SET status = ?1, started_at = ?2
WHERE id = ?3
`

type MarkRunRunningParams struct {
	Status    string
	StartedAt sql.NullString
	ID        string
}

func (q *Queries) MarkRunRunning(ctx context.Context, arg MarkRunRunningParams) error {
	_, err := q.db.ExecContext(ctx, markRunRunning, arg.Status, arg.StartedAt, arg.ID)
	return err
}

const setEnvScheduleNextRun = `-- name: SetEnvScheduleNextRun :exec
UPDATE renart_schedules
SET next_run_at = ?1
WHERE pipeline_id = ?2 AND environment = ?3
`

type SetEnvScheduleNextRunParams struct {
	NextRunAt   sql.NullString
	PipelineID  string
	Environment string
}

func (q *Queries) SetEnvScheduleNextRun(ctx context.Context, arg SetEnvScheduleNextRunParams) error {
	_, err := q.db.ExecContext(ctx, setEnvScheduleNextRun, arg.NextRunAt, arg.PipelineID, arg.Environment)
	return err
}

const setEnvScheduleStatus = `-- name: SetEnvScheduleStatus :exec
UPDATE renart_schedules
SET status = ?1, archived_reason = ?2, updated_at = ?3
WHERE pipeline_id = ?4 AND environment = ?5
`

type SetEnvScheduleStatusParams struct {
	Status         string
	ArchivedReason string
	UpdatedAt      string
	PipelineID     string
	Environment    string
}

func (q *Queries) SetEnvScheduleStatus(ctx context.Context, arg SetEnvScheduleStatusParams) error {
	_, err := q.db.ExecContext(ctx, setEnvScheduleStatus,
		arg.Status,
		arg.ArchivedReason,
		arg.UpdatedAt,
		arg.PipelineID,
		arg.Environment,
	)
	return err
}

const setRunExecutionContext = `-- name: SetRunExecutionContext :execrows
UPDATE pipeline_runs
SET environment = ?1,
    win_start = ?2,
    win_end = ?3,
    full_refresh = ?4,
    backfill = ?5,
    sensor_mode = ?6,
    execution_context_resolved = 1
WHERE id = ?7 AND status IN ('queued', 'running')
`

type SetRunExecutionContextParams struct {
	Environment string
	WinStart    sql.NullString
	WinEnd      sql.NullString
	FullRefresh int64
	Backfill    int64
	SensorMode  string
	ID          string
}

func (q *Queries) SetRunExecutionContext(ctx context.Context, arg SetRunExecutionContextParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setRunExecutionContext,
		arg.Environment,
		arg.WinStart,
		arg.WinEnd,
		arg.FullRefresh,
		arg.Backfill,
		arg.SensorMode,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setRunRiverJob = `-- name: SetRunRiverJob :exec
UPDATE pipeline_runs
SET river_job_id = ?1
WHERE id = ?2
`

type SetRunRiverJobParams struct {
	RiverJobID sql.NullInt64
	ID         string
}

func (q *Queries) SetRunRiverJob(ctx context.Context, arg SetRunRiverJobParams) error {
	_, err := q.db.ExecContext(ctx, setRunRiverJob, arg.RiverJobID, arg.ID)
	return err
}

const setRunSnapshotVersion = `-- name: SetRunSnapshotVersion :exec
UPDATE pipeline_runs
SET snapshot_version_id = ?1
WHERE id = ?2
`

type SetRunSnapshotVersionParams struct {
	SnapshotVersionID sql.NullString
	ID                string
}

func (q *Queries) SetRunSnapshotVersion(ctx context.Context, arg SetRunSnapshotVersionParams) error {
	_, err := q.db.ExecContext(ctx, setRunSnapshotVersion, arg.SnapshotVersionID, arg.ID)
	return err
}

const setScheduleEnabled = `-- name: SetScheduleEnabled :exec
INSERT INTO pipeline_schedule_settings (pipeline_id, enabled, updated_at)
VALUES (?1, ?2, ?3)
ON CONFLICT(pipeline_id) DO UPDATE SET enabled = excluded.enabled, updated_at = excluded.updated_at
`

type SetScheduleEnabledParams struct {
	PipelineID string
	Enabled    int64
	UpdatedAt  string
}

func (q *Queries) SetScheduleEnabled(ctx context.Context, arg SetScheduleEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setScheduleEnabled, arg.PipelineID, arg.Enabled, arg.UpdatedAt)
	return err
}

const setScheduleWatermark = `-- name: SetScheduleWatermark :exec
INSERT INTO schedule_watermarks (pipeline, up_to)
VALUES (?1, ?2)
ON CONFLICT(pipeline) DO UPDATE SET up_to = excluded.up_to
`

type SetScheduleWatermarkParams struct {
	Pipeline string
	UpTo     string
}

func (q *Queries) SetScheduleWatermark(ctx context.Context, arg SetScheduleWatermarkParams) error {
	_, err := q.db.ExecContext(ctx, setScheduleWatermark, arg.Pipeline, arg.UpTo)
	return err
}

const upsertEnvSchedule = `-- name: UpsertEnvSchedule :exec
INSERT INTO renart_schedules (pipeline_id, environment, snapshot_version_id, cron, timezone, vars, catchup_policy, status, archived_reason, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11)
ON CONFLICT(pipeline_id, environment) DO UPDATE SET
    snapshot_version_id = excluded.snapshot_version_id,
    cron = excluded.cron,
    timezone = excluded.timezone,
    vars = excluded.vars,
    catchup_policy = excluded.catchup_policy,
    status = excluded.status,
    archived_reason = excluded.archived_reason,
    updated_at = excluded.updated_at
`

type UpsertEnvScheduleParams struct {
	PipelineID        string
	Environment       string
	SnapshotVersionID string
	Cron              string
	Timezone          string
	Vars              sql.NullString
	CatchupPolicy     string
	Status            string
	ArchivedReason    string
	CreatedAt         string
	UpdatedAt         string
}

func (q *Queries) UpsertEnvSchedule(ctx context.Context, arg UpsertEnvScheduleParams) error {
	_, err := q.db.ExecContext(ctx, upsertEnvSchedule,
		arg.PipelineID,
		arg.Environment,
		arg.SnapshotVersionID,
		arg.Cron,
		arg.Timezone,
		arg.Vars,
		arg.CatchupPolicy,
		arg.Status,
		arg.ArchivedReason,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertRunStep = `-- name: UpsertRunStep :exec
INSERT INTO pipeline_run_steps (run_id, asset, status, started_at, finished_at, error)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT(run_id, asset) DO UPDATE SET
    status = excluded.status,
    started_at = COALESCE(pipeline_run_steps.started_at, excluded.started_at),
    finished_at = excluded.finished_at,
    error = excluded.error
`

type UpsertRunStepParams struct {
	RunID      string
	Asset      string
	Status     string
	StartedAt  sql.NullString
	FinishedAt sql.NullString
	Error      sql.NullString
}

func (q *Queries) UpsertRunStep(ctx context.Context, arg UpsertRunStepParams) error {
	_, err := q.db.ExecContext(ctx, upsertRunStep,
		arg.RunID,
		arg.Asset,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Error,
	)
	return err
}
