// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package storedb

import (
	"context"
	"database/sql"
)

const appendRunLog = `-- name: AppendRunLog :exec
INSERT INTO pipeline_run_logs (run_id, at, line)
VALUES (?1, ?2, ?3)
`

type AppendRunLogParams struct {
	RunID string
	At    string
	Line  string
}

func (q *Queries) AppendRunLog(ctx context.Context, arg AppendRunLogParams) error {
	_, err := q.db.ExecContext(ctx, appendRunLog, arg.RunID, arg.At, arg.Line)
	return err
}

const countActiveRuns = `-- name: CountActiveRuns :one
SELECT COUNT(*)
FROM pipeline_runs
WHERE pipeline_id = ?1 AND status IN (?2, ?3)
`

type CountActiveRunsParams struct {
	PipelineID    string
	QueuedStatus  string
	RunningStatus string
}

func (q *Queries) CountActiveRuns(ctx context.Context, arg CountActiveRunsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveRuns, arg.PipelineID, arg.QueuedStatus, arg.RunningStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRuns = `-- name: CountRuns :one
SELECT COUNT(*)
FROM pipeline_runs
WHERE (CAST(?1 AS TEXT) = '' OR pipeline_id = CAST(?1 AS TEXT))
  AND (
    CAST(?2 AS TEXT) = ''
    OR (CAST(?2 AS TEXT) = 'default' AND (environment = CAST(?2 AS TEXT) OR environment = ''))
    OR (CAST(?2 AS TEXT) <> 'default' AND environment = CAST(?2 AS TEXT))
  )
  AND (CAST(?3 AS TEXT) = '' OR status = CAST(?3 AS TEXT))
  AND (
    CAST(?4 AS TEXT) = ''
    OR LOWER(id) LIKE CAST(?4 AS TEXT)
    OR LOWER(pipeline) LIKE CAST(?4 AS TEXT)
    OR LOWER(pipeline_id) LIKE CAST(?4 AS TEXT)
  )
`

type CountRunsParams struct {
	PipelineID  string
	Environment string
	Status      string
	QueryLike   string
}

func (q *Queries) CountRuns(ctx context.Context, arg CountRunsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRuns,
		arg.PipelineID,
		arg.Environment,
		arg.Status,
		arg.QueryLike,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRun = `-- name: CreateRun :exec
INSERT INTO pipeline_runs (id, pipeline_id, pipeline, environment, trigger, status, win_start, win_end, started_at, finished_at, error, log_ref)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)
`

type CreateRunParams struct {
	ID          string
	PipelineID  string
	Pipeline    string
	Environment string
	Trigger     string
	Status      string
	WinStart    sql.NullString
	WinEnd      sql.NullString
	StartedAt   sql.NullString
	FinishedAt  sql.NullString
	Error       sql.NullString
	LogRef      sql.NullString
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) error {
	_, err := q.db.ExecContext(ctx, createRun,
		arg.ID,
		arg.PipelineID,
		arg.Pipeline,
		arg.Environment,
		arg.Trigger,
		arg.Status,
		arg.WinStart,
		arg.WinEnd,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Error,
		arg.LogRef,
	)
	return err
}

const finishOpenRunSteps = `-- name: FinishOpenRunSteps :exec
UPDATE pipeline_run_steps
SET status = ?1,
    finished_at = ?2,
    error = CASE WHEN CAST(?3 AS TEXT) = '' THEN error ELSE CAST(?3 AS TEXT) END
WHERE run_id = ?4 AND finished_at IS NULL
`

type FinishOpenRunStepsParams struct {
	Status     string
	FinishedAt sql.NullString
	Error      string
	RunID      string
}

func (q *Queries) FinishOpenRunSteps(ctx context.Context, arg FinishOpenRunStepsParams) error {
	_, err := q.db.ExecContext(ctx, finishOpenRunSteps,
		arg.Status,
		arg.FinishedAt,
		arg.Error,
		arg.RunID,
	)
	return err
}

const finishRun = `-- name: FinishRun :exec
UPDATE pipeline_runs
SET status = ?1, finished_at = ?2, error = ?3
WHERE id = ?4
`

type FinishRunParams struct {
	Status     string
	FinishedAt sql.NullString
	Error      sql.NullString
	ID         string
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) error {
	_, err := q.db.ExecContext(ctx, finishRun,
		arg.Status,
		arg.FinishedAt,
		arg.Error,
		arg.ID,
	)
	return err
}

const getRun = `-- name: GetRun :one
SELECT id, pipeline_id, pipeline, environment, trigger, status, win_start, win_end, started_at, finished_at, error, log_ref
FROM pipeline_runs
WHERE id = ?1
`

func (q *Queries) GetRun(ctx context.Context, id string) (PipelineRun, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Pipeline,
		&i.Environment,
		&i.Trigger,
		&i.Status,
		&i.WinStart,
		&i.WinEnd,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.LogRef,
	)
	return i, err
}

const getScheduleEnabled = `-- name: GetScheduleEnabled :one
SELECT enabled
FROM pipeline_schedule_settings
WHERE pipeline_id = ?1
`

func (q *Queries) GetScheduleEnabled(ctx context.Context, pipelineID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getScheduleEnabled, pipelineID)
	var enabled int64
	err := row.Scan(&enabled)
	return enabled, err
}

const getScheduleWatermark = `-- name: GetScheduleWatermark :one
SELECT up_to
FROM schedule_watermarks
WHERE pipeline = ?1
`

func (q *Queries) GetScheduleWatermark(ctx context.Context, pipeline string) (string, error) {
	row := q.db.QueryRowContext(ctx, getScheduleWatermark, pipeline)
	var up_to string
	err := row.Scan(&up_to)
	return up_to, err
}

const listRunLogs = `-- name: ListRunLogs :many
SELECT at, line
FROM pipeline_run_logs
WHERE run_id = ?1
ORDER BY seq ASC
`

type ListRunLogsRow struct {
	At   string
	Line string
}

func (q *Queries) ListRunLogs(ctx context.Context, runID string) ([]ListRunLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunLogs, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunLogsRow
	for rows.Next() {
		var i ListRunLogsRow
		if err := rows.Scan(&i.At, &i.Line); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunSteps = `-- name: ListRunSteps :many
SELECT run_id, asset, status, started_at, finished_at, error
FROM pipeline_run_steps
WHERE run_id = ?1
ORDER BY COALESCE(started_at, finished_at, '') ASC, asset ASC
`

func (q *Queries) ListRunSteps(ctx context.Context, runID string) ([]PipelineRunStep, error) {
	rows, err := q.db.QueryContext(ctx, listRunSteps, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PipelineRunStep
	for rows.Next() {
		var i PipelineRunStep
		if err := rows.Scan(
			&i.RunID,
			&i.Asset,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, pipeline_id, pipeline, environment, trigger, status, win_start, win_end, started_at, finished_at, error, log_ref
FROM pipeline_runs
WHERE (CAST(?1 AS TEXT) = '' OR pipeline_id = CAST(?1 AS TEXT))
  AND (
    CAST(?2 AS TEXT) = ''
    OR (CAST(?2 AS TEXT) = 'default' AND (environment = CAST(?2 AS TEXT) OR environment = ''))
    OR (CAST(?2 AS TEXT) <> 'default' AND environment = CAST(?2 AS TEXT))
  )
  AND (CAST(?3 AS TEXT) = '' OR status = CAST(?3 AS TEXT))
  AND (
    CAST(?4 AS TEXT) = ''
    OR LOWER(id) LIKE CAST(?4 AS TEXT)
    OR LOWER(pipeline) LIKE CAST(?4 AS TEXT)
    OR LOWER(pipeline_id) LIKE CAST(?4 AS TEXT)
  )
ORDER BY COALESCE(started_at, '') DESC, id DESC
LIMIT ?6 OFFSET ?5
`

type ListRunsParams struct {
	PipelineID  string
	Environment string
	Status      string
	QueryLike   string
	Offset      int64
	Limit       int64
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]PipelineRun, error) {
	rows, err := q.db.QueryContext(ctx, listRuns,
		arg.PipelineID,
		arg.Environment,
		arg.Status,
		arg.QueryLike,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PipelineRun
	for rows.Next() {
		var i PipelineRun
		if err := rows.Scan(
			&i.ID,
			&i.PipelineID,
			&i.Pipeline,
			&i.Environment,
			&i.Trigger,
			&i.Status,
			&i.WinStart,
			&i.WinEnd,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
			&i.LogRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRunRunning = `-- name: MarkRunRunning :exec
UPDATE pipeline_runs
SET status = ?1, started_at = ?2
WHERE id = ?3
`

type MarkRunRunningParams struct {
	Status    string
	StartedAt sql.NullString
	ID        string
}

func (q *Queries) MarkRunRunning(ctx context.Context, arg MarkRunRunningParams) error {
	_, err := q.db.ExecContext(ctx, markRunRunning, arg.Status, arg.StartedAt, arg.ID)
	return err
}

const setScheduleEnabled = `-- name: SetScheduleEnabled :exec
INSERT INTO pipeline_schedule_settings (pipeline_id, enabled, updated_at)
VALUES (?1, ?2, ?3)
ON CONFLICT(pipeline_id) DO UPDATE SET enabled = excluded.enabled, updated_at = excluded.updated_at
`

type SetScheduleEnabledParams struct {
	PipelineID string
	Enabled    int64
	UpdatedAt  string
}

func (q *Queries) SetScheduleEnabled(ctx context.Context, arg SetScheduleEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setScheduleEnabled, arg.PipelineID, arg.Enabled, arg.UpdatedAt)
	return err
}

const setScheduleWatermark = `-- name: SetScheduleWatermark :exec
INSERT INTO schedule_watermarks (pipeline, up_to)
VALUES (?1, ?2)
ON CONFLICT(pipeline) DO UPDATE SET up_to = excluded.up_to
`

type SetScheduleWatermarkParams struct {
	Pipeline string
	UpTo     string
}

func (q *Queries) SetScheduleWatermark(ctx context.Context, arg SetScheduleWatermarkParams) error {
	_, err := q.db.ExecContext(ctx, setScheduleWatermark, arg.Pipeline, arg.UpTo)
	return err
}

const upsertRunStep = `-- name: UpsertRunStep :exec
INSERT INTO pipeline_run_steps (run_id, asset, status, started_at, finished_at, error)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT(run_id, asset) DO UPDATE SET
    status = excluded.status,
    started_at = COALESCE(pipeline_run_steps.started_at, excluded.started_at),
    finished_at = excluded.finished_at,
    error = excluded.error
`

type UpsertRunStepParams struct {
	RunID      string
	Asset      string
	Status     string
	StartedAt  sql.NullString
	FinishedAt sql.NullString
	Error      sql.NullString
}

func (q *Queries) UpsertRunStep(ctx context.Context, arg UpsertRunStepParams) error {
	_, err := q.db.ExecContext(ctx, upsertRunStep,
		arg.RunID,
		arg.Asset,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Error,
	)
	return err
}
