[package]
name = "ty_wasi"
version = "0.0.0"
publish = false
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[lib]
crate-type = ["cdylib"]
doctest = false
test = false

[dependencies]
ty_project = { workspace = true, default-features = false, features = [
    "deflate",
    "format",
] }
ty_ide = { workspace = true }
ty_python_core = { workspace = true }

ruff_db = { workspace = true, default-features = false, features = [] }
ruff_diagnostics = { workspace = true }
ruff_notebook = { workspace = true }
ruff_python_formatter = { workspace = true }
ruff_source_file = { workspace = true }
ruff_text_size = { workspace = true }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[lints]
workspace = true
