from typing import Any, Hashable, Iterable, Mapping, Sequence

class DataFrame:
    @property
    def columns(self) -> Any: ...
    @property
    def dtypes(self) -> Any: ...
    @property
    def empty(self) -> bool: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    def __getitem__(self, key: Any) -> Any: ...
    def assign(self, **kwargs: Any) -> DataFrame: ...
    def copy(self, deep: bool = True) -> DataFrame: ...
    def head(self, n: int = 5) -> DataFrame: ...
    def merge(self, right: DataFrame, **kwargs: Any) -> DataFrame: ...
    def rename(self, **kwargs: Any) -> DataFrame: ...
    def sort_values(self, by: Hashable | Sequence[Hashable], **kwargs: Any) -> DataFrame: ...
    def tail(self, n: int = 5) -> DataFrame: ...
    def to_dict(self, orient: str = "dict", **kwargs: Any) -> dict[Any, Any]: ...
