from datetime import date, datetime
from typing import Any

class _Context:
    @property
    def start_date(self) -> date | None: ...
    @property
    def start_datetime(self) -> datetime | None: ...
    @property
    def end_date(self) -> date | None: ...
    @property
    def end_datetime(self) -> datetime | None: ...
    @property
    def execution_date(self) -> datetime | None: ...
    @property
    def pipeline(self) -> str | None: ...
    @property
    def asset_name(self) -> str | None: ...
    @property
    def connection(self) -> str | None: ...
    @property
    def run_id(self) -> str | None: ...
    @property
    def is_full_refresh(self) -> bool: ...
    @property
    def vars(self) -> dict[str, Any]: ...

context: _Context
